imports_granularity = "Module"
tab_spaces = 2
wrap_comments = true
short_array_element_width_threshold = 16
overflow_delimited_expr = true
max_width = 120
chain_width = 80
struct_lit_width = 80
struct_variant_width = 80
