name: Push actions

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  build:
    name: Build release binary for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
      - name: Install cross-rs
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build on ${{ matrix.target }}
        run: cross build --release --target=${{ matrix.target }}
      - name: Upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flow-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/flow
